"""empty message

Revision ID: 01cc7bad4dfc
Revises: 681aab7affb6
Create Date: 2024-04-12 09:53:43.142044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01cc7bad4dfc'
down_revision = '681aab7affb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_order', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('sub_total',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('tax',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('discounts',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('vat',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('comments',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('delivery_period',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_order', schema=None) as batch_op:
        batch_op.alter_column('delivery_period',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('comments',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('vat',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('discounts',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('tax',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('sub_total',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
