"""empty message

Revision ID: 681aab7affb6
Revises: cda9a907865f
Create Date: 2024-04-12 09:45:37.255648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '681aab7affb6'
down_revision = 'cda9a907865f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))

    with op.batch_alter_table('quote_request', schema=None) as batch_op:
        batch_op.alter_column('created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_request', schema=None) as batch_op:
        batch_op.alter_column('created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('quote_order', schema=None) as batch_op:
        batch_op.drop_column('total')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
